UNDataForum/design-system

- packages/components/src/icons/CloseIcon/CloseIcon.js
- packages/components/src/icons/MenuIcon/MenuIcon.js
- packages/components/src/icons/TwitterIcon/TwitterIcon.js
- packages/components/src/icons/TwitterIcon/TwitterIcon.stories.js
- packages/components/src/icons/TwitterIcon/index.js
- packages/components/src/icons/index.js
> feat: Add Twitter icon

- packages/components/package.json
- yarn.lock
> remove prism-react-renderer

- packages/components/.storybook/addons.js
- packages/components/.storybook/config.js
- packages/components/package.json
- packages/tokens/.storybook/addons.js
- packages/tokens/.storybook/config.js
- packages/tokens/package.json
- yarn.lock
> Add a11y plugin to Storybook

- .changeset/eight-moons-march.md
- packages/components/package.json
- packages/components/src/components/Button/Button.stories.js
- packages/components/src/index.js
> Add Button component

- .changeset/serious-fans-hunt.md
- packages/tokens/.storybook/config.js
- packages/tokens/package.json
> Remove @undataforum/components dep from @undataforum/tokens

- .changeset/moody-ways-fail.md
- .gitignore
- now.json
- package.json
- packages/components/package.json
- packages/tokens/package.json
> Simplify Zeit Now config (zero config)

- .changeset/twelve-baboons-camp.md
- packages/components/.storybook/config.js
- packages/components/package.json
- packages/components/src/components/SmartLink/SmartLink.js
- packages/components/src/types.js
- packages/tokens/.storybook/config.js
- packages/tokens/package.json
- yarn.lock
> Export ThemeProvider

- .changeset/eighty-lions-notice.md
- packages/components/src/components/Footer/Footer.js
- packages/components/src/components/Header/Header.js
- packages/components/src/components/SmartLink/SmartLink.js
- packages/components/src/components/SmartLink/SmartLink.stories.js
- packages/components/src/components/SmartLink/index.js
- packages/components/src/components/SocialIcon/SocialIcon.js
- packages/components/src/components/SocialIcon/SocialIcon.stories.js
- packages/components/src/theme.js
- packages/components/src/types.js
> Clean up types

- .changeset/old-eggs-draw.md
- package.json
- packages/components/README.md
- packages/components/package.json
- packages/components/src/components/PostPreview/PostPreview.js
- packages/components/src/components/PostPreview/PostPreview.stories.js
- packages/tokens/package.json
> Add call to action to PostPreview

- .changeset/fast-singers-watch.md
- packages/components/src/components/PostPreview/PostPreview.js
- packages/components/src/components/PostPreview/PostPreview.stories.js
> Rename lead prop to description in PostPreview

- .changeset/unlucky-weeks-provide.md
- packages/components/src/components/DummyLogo/DummyLogo.js
> Change types of height and width in DummyLogo

- .changeset/nice-tables-think.md
- .changeset/unlucky-weeks-provide.md
- packages/components/package.json
- packages/components/src/theme.js
- yarn.lock
> Use deepmerge instead of lodash.merge

- .changeset/plenty-trees-unite.md
- packages/components/src/components/Container/Container.js
> Fix px of footer container on small screens

- package.json
- renovate.json
- yarn.lock
> Group @changesets packages in renovate.json

- .changeset/loud-shoes-do.md
- packages/components/src/components/Header/Header.js
> Fix unwanted margins in header navigation

- .changeset/tidy-camels-doubt.md
- yarn.lock
> Update Theme UI to v0.2.46

- .changeset/thin-wombats-matter.md
- packages/assets/package.json
- packages/components/package.json
> Fix invalid repository prop in all package.json files

- .changeset/early-dancers-prove.md
- packages/components/src/theme.js
> Fix links remaining in hover state on touch

- .changeset/pink-queens-leave.md
- packages/components/src/components/Names/Names.js
- packages/components/src/components/Names/Names.stories.js
- packages/components/src/components/Names/index.js
- packages/components/src/components/index.js
- packages/components/src/index.js
- packages/components/src/theme.js
> Add Names component

- packages/components/src/components/EventPreview/EventPreview.stories.js
- packages/components/src/components/PostPreview/PostPreview.stories.js
> Use Names component in stories

- .changeset/long-shirts-promise.md
- .changeset/rich-monkeys-judge.md
- packages/components/src/components/Badge/Badge.js
- packages/components/src/components/Badge/Badge.stories.js
- packages/components/src/components/Badge/index.js
- packages/components/src/components/Badges/Badges.js
- packages/components/src/components/Badges/Badges.stories.js
- packages/components/src/components/Badges/index.js
- packages/components/src/components/EventPreview/EventPreview.js
- packages/components/src/components/FlexList/FlexList.js
- packages/components/src/components/FlexList/FlexList.stories.js
- packages/components/src/components/ProfilePreview/ProfilePreview.js
- packages/components/src/theme.js
- packages/components/src/types.js
> Add Badges component

- .changeset/chilled-experts-hammer.md
- packages/components/src/components/FlexList/FlexList.js
- packages/components/src/components/PostPreview/PostPreview.stories.js
- packages/components/src/components/ProfilePreview/ProfilePreview.js
- packages/components/src/components/ProfilePreview/ProfilePreview.stories.js
- packages/components/src/theme.js
> Use variants for alignment in ProfilePreview

- .changeset/fifty-rice-fold.md
- packages/components/src/components/ProfilePreview/ProfilePreview.js
- packages/components/src/components/ProfilePreview/ProfilePreview.stories.js
> Remove implicit link from ProfilePreview

- .changeset/quiet-beers-lie.md
- packages/components/src/components/Avatars/Avatars.js
- packages/components/src/components/Avatars/Avatars.stories.js
- packages/components/src/components/Avatars/index.js
- packages/components/src/components/EventPreview/EventPreview.stories.js
- packages/components/src/components/PostPreview/PostPreview.stories.js
- packages/components/src/components/index.js
- packages/components/src/index.js
> Add Avatar component

- .changeset/fuzzy-bobcats-clean.md
- packages/components/src/index.js
> Remove GitHubIcons and TwitterIcons from exports

- .changeset/chilly-chairs-roll.md
- packages/components/src/index.js
> Export Grid from @theme-ui/components

- .changeset/lovely-queens-tease.md
- packages/components/src/components/Header/Header.js
> Fix close navigation button on iPhone

- .changeset/two-foxes-knock.md
- packages/components/src/components/EventPreview/EventPreview.js
- packages/components/src/components/EventPreview/EventPreview.stories.js
> Let render props control spacing in EventPreview

- .changeset/few-actors-leave.md
- packages/components/src/components/EventPreview/EventPreview.js
- packages/components/src/components/EventPreview/EventPreview.stories.js
> Fix margins in EventPreview

- .changeset/light-singers-flash.md
- packages/components/src/components/EventPreview/EventPreview.js
- packages/components/src/components/EventPreview/EventPreview.stories.js
> Align buttons when EventPreviews are grid rendered

- .changeset/sour-weeks-sip.md
- packages/components/src/components/EventPreview/EventPreview.js
> Fix bottom margin of date/time comp (EventPreview)

- .changeset/shiny-cats-boil.md
- packages/components/src/components/Container/Container.js
- packages/components/src/components/EventPreview/EventPreview.stories.js
- packages/components/src/components/Footer/Footer.js
- packages/components/src/components/Header/Header.js
> Change default padding for Container

- .changeset/chilly-cheetahs-retire.md
- packages/components/src/components/Footer/Footer.js
> Always stretch Footer to edges

- .changeset/fast-snails-hammer.md
- packages/components/src/components/Container/Container.js
- packages/components/src/components/Hero/Hero.js
> Constrain width of image in Hero

- .changeset/gentle-rabbits-return.md
- packages/components/src/components/EventPreview/EventPreview.js
- packages/components/src/components/Hero/Hero.js
- packages/components/src/components/Hero/Hero.stories.js
- packages/components/src/theme.js
> Add promo prop to Hero

- .changeset/real-badgers-fail.md
- packages/components/src/index.js
> Export Card component from @theme-ui/components

- .changeset/cuddly-wombats-unite.md
- packages/components/src/components/Hero/Hero.js
> Fix spacing in Hero

- .changeset/hungry-melons-agree.md
- packages/components/src/theme.js
> Remove props from theme in favor of preset

- .changeset/tender-gifts-argue.md
- packages/components/src/theme.js
> Make round corners default

- .changeset/many-hounds-return.md
- packages/components/src/index.js
> Export NewTabLink

- .changeset/fuzzy-ties-rhyme.md
- packages/components/src/index.js
- yarn.lock
> Export Link from @theme-ui/components

- .changeset/popular-garlics-appear.md
- packages/components/src/components/EventPreview/EventPreview.js
- packages/components/src/components/PostPreview/PostPreview.js
- packages/components/src/components/PostPreview/PostPreview.stories.js
> Align buttons of PostPreview inside Grid

- .changeset/odd-ravens-sin.md
- packages/components/src/components/YouTube/YouTube.js
- packages/components/src/components/YouTube/YouTube.stories.js
- packages/components/src/components/YouTube/index.js
- packages/components/src/components/index.js
- packages/components/src/index.js
> Add YouTube component

- .changeset/flat-pears-compare.md
- packages/components/src/components/YouTube/YouTube.js
> Add support for spacing props to YouTube component

- .changeset/slow-impalas-drive.md
- packages/components/src/components/YouTube/YouTube.js
> Undo support for changeset props

- .changeset/witty-balloons-love.md
- packages/components/src/components/Video/Video.js
- packages/components/src/components/Video/Video.stories.js
- packages/components/src/components/Video/index.js
- packages/components/src/components/YouTube/index.js
- packages/components/src/components/index.js
- packages/components/src/index.js
> Rename YouTube to Video

- .changeset/itchy-plums-marry.md
- packages/components/src/components/Video/Video.js
> Revise player parameters

- .changeset/hungry-sheep-fold.md
- packages/components/package.json
- packages/components/src/components/Header/Header.js
- packages/components/src/theme.js
- yarn.lock
> Fix Header maxWidth

- .changeset/smart-needles-roll.md
- packages/components/src/components/Header/Header.js
- packages/components/src/components/Header/Header.stories.js
- packages/components/src/components/SmartLink/SmartLink.js
> Fix link text acccessibility warnings in Header

- .changeset/chilled-steaks-beg.md
- .changeset/khaki-jokes-lay.md
- .changeset/red-seahorses-tease.md
- packages/components/src/components/Avatars/Avatars.js
- packages/components/src/components/Badge/Badge.js
- packages/components/src/components/Badge/Badge.stories.js
- packages/components/src/components/Badge/index.js
- packages/components/src/components/Badges/Badges.js
- packages/components/src/components/Badges/Badges.stories.js
- packages/components/src/components/ProfilePreview/ProfilePreview.js
- packages/components/src/components/ProfilePreview/ProfilePreview.stories.js
- packages/components/src/index.js
- packages/components/src/theme.js
- packages/components/src/types.js
> Refactor Badges and dependent components

- .changeset/funny-timers-confess.md
- packages/components/src/components/Avatars/Avatars.js
- packages/components/src/components/EventPreview/EventPreview.js
- packages/components/src/components/EventPreview/EventPreview.stories.js
- packages/components/src/components/ProfilePreview/ProfilePreview.stories.js
> Add custom colors support to EventPreview

- .changeset/kind-beans-shake.md
- packages/components/src/components/PostPreview/PostPreview.js
- packages/components/src/components/PostPreview/PostPreview.stories.js
> Add custom colors support to PostPreview

- .changeset/good-glasses-refuse.md
- packages/components/src/components/Footer/Footer.js
> Increase Footer top and bottom padding

- .changeset/clever-readers-thank.md
- packages/components/src/components/Footer/Footer.js
- packages/components/src/components/Header/Header.js
- packages/components/src/components/SmartLink/SmartLink.js
- packages/components/src/components/SocialIcons/SocialIcons.js
- packages/components/src/theme.js
> Clean up color pairings

- .changeset/silly-bees-attend.md
- packages/components/src/components/EventPreview/EventPreview.js
> Add spacing around type tag in EventPreview

- .changeset/gentle-cats-greet.md
- .changeset/plenty-donkeys-attend.md
- .changeset/strange-carrots-thank.md
- packages/components/src/components/Avatars/Avatars.js
- packages/components/src/components/Avatars/Avatars.stories.js
- packages/components/src/components/EventPreview/EventPreview.js
- packages/components/src/components/EventPreview/EventPreview.stories.js
- packages/components/src/components/Names/Names.js
- packages/components/src/components/Names/Names.stories.js
> Add align prop to EventPreview

- .changeset/dull-birds-turn.md
- .changeset/old-doors-guess.md
- .changeset/sharp-rice-drum.md
- package.json
- packages/assets/.babelrc
- packages/assets/.npmignore
- packages/assets/babel.config.js
- packages/assets/package.json
- packages/components/.npmignore
- packages/components/package.json
- packages/preset/package.json
- yarn.lock
> Use microbundle to build packages

- .changeset/metal-poems-kneel.md
- packages/assets/package.json
- packages/components/package.json
> Use microbundle with --jsx option

- .changeset/tidy-drinks-call.md
- packages/components/package.json
- yarn.lock
> Add theme-ui to peerDependencies

- .changeset/famous-chicken-think.md
- packages/components/.babelrc
- packages/components/.npmignore
- packages/components/babel.config.js
> Prevent obsolete files from being copied into pkg

- .changeset/quiet-pots-brush.md
- packages/components/src/components/Header/Header.js
> Fix background in Header nav on small screens

- .changeset/real-bats-tease.md
- packages/components/src/components/EventPreview/EventPreview.js
- packages/components/src/components/EventPreview/EventPreview.stories.js
> Make align prop in EventPreview responsive

- renovate.json
> Run Renoavate Bot every weekend only

- packages/preset/package.json
> Fix purge script

- .github/workflows/release.yml
> Add GitHub action for releases

- README.md
- package.json
> Add release script

- .github/workflows/release.yml
- README.md
> Automate publishing to NPM

- .changeset/friendly-owls-mix.md
- packages/components/src/components/Names/Names.js
> Make align type in Names responsive

- .changeset/forty-hats-poke.md
- .changeset/lazy-kangaroos-deny.md
- packages/components/config/storybook/preview.js
- packages/preset/src/colors.js
> Clean up Storybook config

- now.json
- package.json
- yarn.lock
> Remove now and now.json

- docs/src/stories/components/Badges.stories.js
- packages/components/src/badges.js
- packages/components/src/event-preview.js
- packages/components/src/profile-preview.js
- packages/components/src/util.js
> Make align prop of Badges compatible with other components

- .changeset/big-laws-swim.md
- docs/src/stories/components/ColorCard.stories.js
- packages/components/src/color-card.js
> Move subtitle into colored header in ColorCard

- .gitignore
- now.json
- package.json
- yarn.lock
> Deploy master branch only after packages released

- .github/workflows/.deploy.yml
- .github/workflows/release.yml
- package.json
> Add missing GitHub action for GH-362

- .changeset/tender-horses-vanish.md
- docs/src/stories/components/EventPreview.stories.js
- packages/components/src/event-preview.js
> Make speakers optional in EventPreview

- .github/workflows/.deploy.yml
> Use amondnet/now-deployment for deploy action

- .changeset/spicy-points-double.md
- docs/src/stories/components/Avatars.stories.js
- docs/src/stories/components/Badges.stories.js
- docs/src/stories/components/ColorCard.stories.js
- docs/src/stories/components/EventPreview.stories.js
- docs/src/stories/components/PostPreview.stories.js
- docs/src/stories/components/ProfilePreview.stories.js
- packages/components/src/avatars.js
- packages/components/src/color-card.js
- packages/components/src/event-preview.js
- packages/components/src/post-preview.js
- packages/components/src/profile-preview.js
> Use composition instead of render props

- .github/workflows/release.yml
- README.md
> Add NOW_TOKEN env variable to release action

- packages/preset/src/colors.js
> Change color pairings for muted color

- .github/workflows/.deploy.yml
> Fix deploy action

- .changeset/real-socks-reflect.md
- packages/preset/package.json
> Fix metadata for @undataforum/preset

- .changeset/stupid-geese-stare.md
- docs/src/stories/components/Footer.stories.js
- docs/src/stories/components/Header.stories.js
- docs/src/stories/components/SmartLink.stories.js
- docs/src/stories/components/SocialIcons.stories.js
- packages/components/src/footer.js
- packages/components/src/header.js
- packages/components/src/smart-link.js
- packages/components/src/social-icons.js
- packages/preset/src/index.js
> Change SmartLink variants

- .changeset/long-mugs-grab.md
- docs/src/stories/components/EmailIcon.stories.js
- docs/src/stories/components/GitHubIcon.stories.js
- docs/src/stories/components/TwitterIcon.stories.js
- packages/components/src/email-icon.js
- packages/components/src/github-icon.js
- packages/components/src/icon.js
- packages/components/src/social-icons.js
- packages/components/src/twitter-icon.js
> Refactor icons with generic Icon component

- .changeset/shy-cougars-scream.md
- docs/src/stories/components/Footer.stories.js
- docs/src/stories/components/ProfilePreview.stories.js
- docs/src/stories/components/SocialIcons.stories.js
- packages/components/src/profile-preview.js
- packages/components/src/social-icons.js
> Add support for social icons in ProfilePreview

- .changeset/afraid-birds-laugh.md
- .changeset/selfish-rules-join.md
- docs/config/storybook/preview.js
- docs/src/stories/components/Avatars.stories.js
- docs/src/stories/components/Badges.stories.js
- docs/src/stories/components/EventPreview.stories.js
- docs/src/stories/components/ProfilePreview.stories.js
- packages/components/src/avatars.js
- packages/components/src/badges.js
- packages/components/src/event-preview.js
- packages/components/src/profile-preview.js
- packages/preset/src/index.js
> Use composition i/o render props in EventPreview

- .changeset/four-horses-wait.md
- .changeset/serious-starfishes-drive.md
- docs/src/stories/components/PostPreview.stories.js
- packages/components/src/post-preview.js
Closes GH-83 and and closes GH-412.
> Refactor PostPreview

- .changeset/twelve-turkeys-shout.md
- docs/src/stories/components/EventPreview.stories.js
- packages/components/src/event-preview.js
> Refactor props of EventPreview

- lint-staged.config.js
- package.json
> Add support for .mdx files in project configs

- .changeset/twelve-flowers-roll.md
- docs/src/stories/components/EmailIcon.stories.js
- docs/src/stories/components/Footer.stories.js
- docs/src/stories/components/GitHubIcon.stories.js
- docs/src/stories/components/SocialIcons.stories.js
- docs/src/stories/components/TwitterIcon.stories.js
- packages/components/src/footer.js
- packages/components/src/icon.js
- packages/components/src/profile-preview.js
- packages/components/src/social-icons.js
> Add align prop to SocialIcons

- renovate.json
> Turn off semantic commits in renovate.json

- .github/workflows/code-qa.yml
- docs/config/storybook/preview.js
- package.json
- packages/components/src/util.js
> Add lint check

- .github/workflows/code-qa.yml
- .github/workflows/release.yml
> Skip Node installation in actions due to node package

- .github/workflows/code-qa.yml
- .github/workflows/release.yml
- package.json
- yarn.lock
> Enforce Node 12.x

- .github/CODEOWNERS
- renovate.json
> Remove reviewers field in renovate.json

- package.json
- yarn.lock
> Remove now dependency

- .github/workflows/code-qa.yml
- .github/workflows/release.yml
- package.json
> Make lint check trigger for publish PR

- .prettierrc
- package.json
- yarn.lock
> Use @maiertech/prettier-config

- docs/README.md
- docs/package.json
- package.json
> Rename `start` scripts  to `dev`

- .changeset/early-zebras-decide.md
- docs/content/components/post-preview.mdx
- docs/src/pages/post-preview/grid-of-posts.js
- docs/src/pages/post-preview/render-with-avatars.js
- docs/src/pages/post-preview/render-with-names.js
- package.json
- packages/components/src/post-preview.js
- yarn.lock
> Add support for tag in PostPreview

- .changeset/yellow-spiders-stare.md
- docs/content/components/event-preview.mdx
- docs/src/pages/event-preview/grid-of-events.js
- docs/src/pages/event-preview/render-with-avatars.js
- docs/src/pages/event-preview/render-with-names.js
- packages/components/src/event-preview.js
> Remove duration from EventPreview

- .changeset/plenty-pans-deliver.md
- docs/content/components/icon.mdx
- docs/content/components/index.mdx
- docs/src/@primer/gatsby-theme-doctocat/nav.yml
- packages/components/README.md
- packages/components/src/index.js
> Export Icon component

- docs/package.json
- yarn.lock
> Remove dotenv package

- docs/src/@primer/gatsby-theme-doctocat/components/live-preview-wrapper.js
- docs/src/@primer/gatsby-theme-doctocat/live-code-scope.js
- yarn.lock
> Add Theme UI's ThemeProvider back to wrapper

- .changeset/calm-peas-hang.md
- docs/content/components/profile-preview.mdx
- docs/src/pages/profile-preview/align-end.js
- docs/src/pages/profile-preview/align-start.js
- docs/src/pages/profile-preview/complete-profile.js
- docs/src/pages/profile-preview/really-long-strings.js
- packages/components/src/profile-preview.js
> Fix the docs for ProfilePreview

- .changeset/orange-ghosts-kick.md
- docs/content/components/profile-preview.mdx
- docs/src/pages/profile-preview/align-end.js
- docs/src/pages/profile-preview/align-start.js
- docs/src/pages/profile-preview/complete-profile.js
- docs/src/pages/profile-preview/really-long-strings.js
- packages/components/src/profile-preview.js
> Eliminate fontSize prop from ProfilePreview

- .changeset/wicked-mice-destroy.md
- docs/content/components/avatars.mdx
- docs/src/pages/avatars/many-avatars.js
- packages/components/src/avatars.js
> Fix incorrect name prop-type in Avatars component

- .changeset/hungry-flies-shop.md
- .changeset/nice-llamas-roll.md
- docs/content/components/post-preview.mdx
- docs/src/pages/post-preview/customize-with-preset.js
- docs/src/pages/post-preview/grid-of-posts.js
- docs/src/pages/post-preview/render-authors-with-avatars.js
- packages/components/src/post-preview.js
- packages/preset/src/index.js
> Fix docs for PostPreview

- .github/dependabot.yml
> Rename .dependabot.yml to dependabot.yml

- .github/dependabot.yml
> Switch Dependabot updates to weekly

- .changeset/curly-vans-build.md
- .changeset/silly-bats-dance.md
- docs/content/components/event-preview.mdx
- docs/content/components/post-preview.mdx
- docs/src/pages/event-preview/customize-with-preset.js
- docs/src/pages/event-preview/grid-of-events.js
- docs/src/pages/event-preview/render-speakers-with-avatars.js
- packages/components/src/event-preview.js
- packages/preset/src/index.js
> Fix docs for EventPreview

- .changeset/seven-items-hide.md
- docs/content/components/avatars.mdx
- docs/content/components/names.mdx
- docs/src/@primer/gatsby-theme-doctocat/nav.yml
- docs/src/pages/names/few-names.js
- docs/src/pages/names/many-names.js
- packages/components/src/names.js
> Migrate stories fo Names component to Doctocat

- .changeset/clever-years-look.md
- docs/content/components/post-preview.mdx
- packages/components/src/post-preview.js
> Fix incorrect spacing in PostPreview

- .changeset/big-emus-hide.md
- docs/content/components/header.mdx
- docs/package.json
- packages/components/src/header.js
- packages/preset/src/index.js
> Remove unwanted borders in mobile navigation in Header

- docs/package.json
- yarn.lock
> Upgrade @primer/gatsby-theme-doctocat to 0.23.0

- .github/workflows/test.yml
> Rename code-qa.yml to test.yml

- .github/dependabot.yml
> Switch Dependabot to monthly updates

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .vscode/extensions.json
- .vscode/settings.json
> Add container configs

- vercel.json
> Remove vercel.json

- .vscode/settings.json
> Remove debug.javascript.autoAttachFilter from workspace settings

- .changeset/giant-ligers-give.md
- packages/preset/src/index.js
> Remove sizes from preset

- .changeset/dry-onions-buy.md
- .changeset/selfish-tigers-tan.md
- .changeset/three-turkeys-shake.md
- docs/content/components/badges.mdx
- docs/content/components/tags.mdx
- docs/src/@primer/gatsby-theme-doctocat/nav.yml
- docs/src/pages/tags/customized-with-preset.js
- docs/src/pages/tags/few-tags.js
- docs/src/pages/tags/many-tags.js
- packages/components/src/badges.js
- packages/components/src/index.js
- packages/components/src/tags.js
- packages/preset/src/index.js
> Add Tags component

- .changeset/sixty-experts-fry.md
- package.json
- packages/assets/package.json
- packages/components/package.json
- yarn.lock
> Upgrade peer dependencies

- package.json
- packages/assets/package.json
- packages/components/package.json
- packages/preset/package.json
- yarn.lock
> Upgrade @maiertech/eslint-config

- docs/package.json
- docs/src/@primer/gatsby-theme-doctocat/components/live-preview-wrapper.js
- yarn.lock
> Fix examples that render with inherent width

- .changeset/new-lions-burn.md
- .changeset/unlucky-toys-wait.md
- docs/content/components/card.mdx
- docs/package.json
- docs/src/pages/card/with-subtitle.js
- docs/src/pages/card/without-subtitle.js
- packages/components/package.json
- packages/preset/package.json
- yarn.lock
> Switch back to theme-ui stable

- .changeset/curvy-ravens-appear.md
- packages/components/src/event-preview.js
> Remove duplicated conditionals in EventPreview

- .huskyrc
- package.json
> Extract husky config from package.json into .huskyrc

- lint-staged.config.js
- package.json
- yarn.lock
> Improve lint-staged config

- .vscode/extensions.json
> Remove comment
